#!/bin/sh
# parameters
# $1 the interface name used by pppd (e.g. ppp3)
# $2 the tty device name
# $3 the tty device speed
# $4 the local IP address for the interface
# $5 the remote IP address
# $6 the parameter specified by the 'ipparam' option to pppd




# Getting the RP-Upstream-Speed-Limit from radius (integer value)
UPLOAD=$(cat /var/run/radattr.$1 | grep -i RP-Upstream-Speed-Limit | awk '{print $2}')
#UPLOAD=8000
if [  -z "$UPLOAD" ]; then
   UPLOAD=8000
   echo "upload down ${UPLOAD}" >> /etc/ppp/abclog
fi
classid=`expr $UPLOAD / 100 + 1`


/usr/sbin/iptables -t mangle -D POSTROUTING -s ${5}/32  -o eth0 -j MARK --set-xmark ${classid}
echo "/usr/sbin/iptables -t mangle -D POSTROUTING -s ${5}/32  -o eth0 -j MARK --set-xmark ${classid}" >> /etc/ppp/abclog

/usr/sbin/iptables -t mangle -D POSTROUTING -o eth0 -s $5  -j RETURN

echo "/usr/sbin/iptables -t mangle -D POSTROUTING -o eth0 -s $5  -j RETURN" >> /etc/ppp/abclog



/usr/sbin/iptables -t filter -D FORWARD -o $1 -j ACCEPT
/usr/sbin/iptables -t nat -D POSTROUTING -o $1 -j MASQUERADE








logfile=/var/log/ppp
echo "`date` $0 $1 $2 $3 $4 $5 $6" >> $logfile





exit 0